### ISSUE TITLE
More tutorials

### ISSUE THREAD

**Issue by wuzhendong2000** [tomflint22/beamWeldFoam#10]
dear originator,excuse me, could you publish more tutorials of laser welding in openFoam10?

**Comment by tomflint22** [comment]
Hi,

Do you mean our other solver laserbeamFoam?

https://github.com/micmog/LaserbeamFoam

If you want to simulate laser-substrate interaction this aserbeamfoam solver is the best one to use, rather than beamweldfoam. The main branch of laserbeamfoam compiles against OpenFoam10.
