### ISSUE TITLE
More Tutorials for OpenFoam 10

### ISSUE THREAD

**Issue by hernan-aparicio** [tomflint22/beamWeldFoam#11]
Can we have more tutorials like Powder Bed Fusion 3D for openfoam 10

**Comment by tomflint22** [comment]
*please* may we have more tutorials, if you have the time for the OpenFoam 10 branch.

I've added the PowderBed3D and EB3D cases to the OF10 branch. All you need to do to update the Openfoam6 tutorials to work with OpenFoam10 is to modify the setfieldsdict to be alpha.phase1 --> alpha.metal, and change the Temperature --> T.

Try copying one of the cases like, EB3d and modfying the blockmesh, setfields and fvsollution files. That's what I've just done.

All the best,
Tom
