### ISSUE TITLE
the EB_3D case can not run because of time step continuity errors

### ISSUE THREAD

**Issue by tunshu1987** [tomflint22/beamWeldFoam#14]
Hello 
I see your article(https://doi.org/10.1016/j.softx.2022.101065) and it's good. When I run the case in the OpenFOAM-6 in Ubuntu system, it run for ArcCase and Tancase successfully and can not run the EB_3D case and SenDavies case. it says error as follow. 
[DICPCG:Solving for p rghInitial residual=2.915706894e-12，Finalresidual =9.876512584e-13.No Iterations 22-1.718705699e-27time step continuity errors:sum local=2.634767435e-37,qlobal=5.202538419e-38, cumulative =DICPCG: Solving for p rgh,Initial residual = 9.876512818e-13, Final residual = 9.876512818e-13, No Iterations 0time step continuity errors :sum local = 2.634767492e-37, global = 5.20253731e-38, cumulative =.-1.718705699e-27DICPcG: Solving for p_rgh, Initial residual = 9.876512818e-13, Final residual = 9.876512818e-13, No Iterations etime step continuity errors : sum local = 2.634767492e-37, global = 5.20253731e-38, cumulative = -1.718705699e-27DICPcG: Solving for p rgh, Initial residual = 9,876512818e-13, Final residual = 9.876512818e-13, No Iterations etime step continuity errors : sum local = 2.634767492e-37, global = 5.20253731e-38, cumulative = -1.718705699e-27巴E softwateupdaten Time=87.6s ClockTime = 96 s]
![error](https://github.com/tomflint22/beamWeldFoam/assets/55968000/f3d3a41b-62f3-4e55-860a-443386970cb0)

I want to confirm if the EB_3D case is to valid the figure 6 in your article(https://doi.org/10.1016/j.softx.2022.101065), and what parameter should I change?

Thanks for any answer in advance!

**Comment by tomflint22** [comment]
Hi,

sorry I don't really maintain this solver too much anymore. You would be better using our laserbeamFoam solver which we actively maintain. It is a much nicer solver. I will be adding the beamweldfoam heat source to the laserbeamfoam solver as an option when I get time

**Comment by tunshu1987** [comment]
anyway Thank you. I will try this laserbeamfoam solver.
