### ISSUE TITLE
Small error in Readme 

### ISSUE THREAD

**Issue by edwin-bergstedt** [tomflint22/beamWeldFoam#3]
In bullet list Laser Welding is spelled wrong. Really interesting project. Will look closer at a later time. Keep up the good work.

**Comment by tomflint22** [comment]
Thanks for the input. If one of the other developers doesn't get to this first I'll fix it in the next few days. Thanks for your interest.

**Comment by tomflint22** [comment]
Hi, I fixed this issue. I also improved the handling of the momentum source term at the fluid/solid interface as it was brought to my attention tat there was another good validation case (Tan). This is now included.

Thanks!
