### ISSUE TITLE
Arc  Pressure  or Pressure to the surface

### ISSUE THREAD

**Issue by d1ma4ek** [tomflint22/beamWeldFoam#8]
Hello Tom. I have done a lot of numerical analyses and the solution describes the result quite well. There are questions.

1) How to change the phase 1 density (rho) for the liquid state in arc welding solvers?
2) How can pressure be added to the surface in the solver? For example, there is a Pvap pressure. But you need pressure to the surface according to the type of heat source. Which part of the code needs to be corrected and add its own pressure in the solver?

**Comment by d1ma4ek** [comment]
Pmax*Foam::pow(2.7182, (-3.0 *Foam::pow( zcoord[cellpointhit],2)/(Foam::pow(a_cond,2)))) something I need to add to the surface

**Comment by tomflint22** [comment]
I think you need to do more reading. Your question is far too broad. If you are interested in a proper treatment for arc welding please see this paper:

https://www.nature.com/articles/s41598-021-97177-8

You can use beamweldfoam for arc cases but it uses a surface Gaussian and neglects the Lorentz forces.
