### ISSUE TITLE
fatal error: dynamicFvMesh.H: No such file or directory

### ISSUE THREAD

**Issue by wuzhendong2000** [tomflint22/beamWeldFoam#9]
afer wmake 
show fatal error: dynamicFvMesh.H: No such file or directory

**Comment by tomflint22** [comment]
Have you installed openfoam 10 before running wclean and wmake?

**Comment by tomflint22** [comment]
And which branch is this on? The OpenFoam 6 or 10 branch? You need to install the appropriate OpenFoam libraries before trying to build the solver

**Comment by wuzhendong2000** [comment]
> Have you installed openfoam 10 before running wclean and wmake?

yes，I have

**Comment by wuzhendong2000** [comment]
I search the src filefolder and I find "dynamicFvMesh.H" don't exist,i don't know why this happened.I successfully ran "laserbeamFoam",but"beamWeldFoam" is failed.

**Comment by tomflint22** [comment]
Are you using the Openfoam10 branch of beamWeldFoam?

**Comment by wuzhendong2000** [comment]
I get it，think you very much!!!

**Comment by tomflint22** [comment]
No problem. Let me know if you have any other issues. I'll make the Openfoam10 branch the main one soon. Just need to make more of the tutorials compatible with OF10
